name: CI/CD Pipeline  # Tên của pipeline

on:  # Chỉ định các sự kiện sẽ kích hoạt pipeline
  push:
    branches:
      - main  # Chạy khi có thay đổi trên nhánh master
  pull_request:
    branches:
      - main  # Chạy khi có pull request vào nhánh master

jobs:
  build:
    runs-on: ubuntu-latest  # Chạy trên môi trường Ubuntu

    steps:  # Các bước trong pipeline
      - name: Checkout code
        uses: actions/checkout@v2  # Kiểm tra mã nguồn từ repository

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'  # Cài đặt phiên bản Node.js

      - name: Install dependencies
        run: npm install  # Cài đặt dependencies

      - name: Build project
        run: npm run build  # Build dự án

      - name: Deploy (example)
        run: |
          echo "Deploying application..."
          # Lệnh deploy của bạn
